name: news_app
description: "News app that obtains articles from the newsapi.org."


  # flutter pub run build_runner build --delete-conflicting-outputs

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  mobx: ^2.3.3+2
  get_it: ^7.7.0
  dio: ^5.4.3+1
  mockito: ^5.4.4
  drift: ^2.17.0
  connectivity_plus: ^6.0.3
  json_annotation: ^4.9.0
  injectable: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  #assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  #fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700